version: '1'

services:
  app:
    image: mbaluev/the-form-client:latest
    container_name: the-form-client
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production