export const VIEW_MODEL = {
  App: Symbol.for('AppViewModel'),
  Auth: Symbol.for('AuthViewModel'),
  Filter: Symbol.for('FilterViewModel'),
  Locale: Symbol.for('LocaleViewModel'),
  Menu: Symbol.for('MenuViewModel'),
  Notify: Symbol.for('NotifyViewModel'),
  Option: Symbol.for('OptionViewModel'),

  Block: Symbol.for('BlockViewModel'),
  Material: Symbol.for('MaterialViewModel'),
  Module: Symbol.for('ModuleViewModel'),
  Question: Symbol.for('QuestionViewModel'),
  Task: Symbol.for('TaskViewModel'),
  User: Symbol.for('UserViewModel'),

  ModuleUser: Symbol.for('ModuleUserViewModel'),
  BlockUser: Symbol.for('BlockUserViewModel'),
  MaterialUser: Symbol.for('MaterialUserViewModel'),
  QuestionUser: Symbol.for('QuestionUserViewModel'),
  TaskUser: Symbol.for('TaskUserViewModel'),
  TaskUserDocument: Symbol.for('TaskUserDocumentViewModel'),

  ModuleAdmin: Symbol.for('ModuleAdminViewModel'),
  BlockAdmin: Symbol.for('BlockAdminViewModel'),
  MaterialAdmin: Symbol.for('MaterialAdminViewModel'),
  QuestionAdmin: Symbol.for('QuestionAdminViewModel'),
  TaskAdmin: Symbol.for('TaskAdminViewModel'),
  TaskAdminDocument: Symbol.for('TaskAdminDocumentViewModel'),
};
